<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DictsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('dicts')->delete();
        
        \DB::table('dicts')->insert(array (
            0 => 
            array (
                'id' => 1,
                'type' => 'dzlx',
                'name' => '行政区划',
                'code' => '4',
                'desc' => '地址类型',
                'value' => 101001,
                'created_at' => '2019-11-29 12:06:33',
                'updated_at' => '2019-11-29 12:06:33',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'type' => 'dzlx',
                'name' => '社区',
                'code' => '2',
                'desc' => '地址类型',
                'value' => 101002,
                'created_at' => '2019-11-29 13:05:58',
                'updated_at' => '2019-11-29 13:05:58',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'type' => 'dzlx',
                'name' => '小区',
                'code' => '3',
                'desc' => '地址类型',
                'value' => 101003,
                'created_at' => '2019-11-29 12:06:33',
                'updated_at' => '2019-11-29 12:06:33',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'type' => 'dzlx',
                'name' => '住宅楼',
                'code' => '5',
                'desc' => '地址类型',
                'value' => 101004,
                'created_at' => '2019-11-29 12:06:33',
                'updated_at' => '2019-11-29 12:06:33',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'type' => 'dzlx',
                'name' => '写字楼',
                'code' => '6',
                'desc' => '地址类型',
                'value' => 101005,
                'created_at' => '2019-11-29 12:06:33',
                'updated_at' => '2020-07-14 01:14:20',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'type' => 'dzlx',
                'name' => '商业区',
                'code' => '7',
                'desc' => '地址类型',
                'value' => 101006,
                'created_at' => '2019-11-29 12:06:33',
                'updated_at' => '2019-11-29 12:06:33',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'type' => 'dzlx',
                'name' => '地址',
                'code' => '0',
                'desc' => '地址类型',
                'value' => 101007,
                'created_at' => '2019-11-29 12:06:33',
                'updated_at' => '2019-11-29 12:06:33',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'type' => 'hylx',
                'name' => '其它',
                'code' => '12',
                'desc' => '行业类型',
                'value' => 102001,
                'created_at' => '2019-12-20 13:29:52',
                'updated_at' => '2019-12-20 13:29:52',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'type' => 'hylx',
                'name' => '医院',
                'code' => '2',
                'desc' => '行业类型',
                'value' => 102002,
                'created_at' => '2019-12-20 13:30:19',
                'updated_at' => '2019-12-20 13:30:19',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'type' => 'hylx',
                'name' => '学校',
                'code' => '3',
                'desc' => '行业类型',
                'value' => 102003,
                'created_at' => '2019-12-20 13:30:42',
                'updated_at' => '2019-12-20 13:30:42',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'type' => 'hylx',
                'name' => '居民',
                'code' => '4',
                'desc' => '行业类型',
                'value' => 102004,
                'created_at' => '2019-12-20 13:31:01',
                'updated_at' => '2019-12-20 13:31:01',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'type' => 'hylx',
                'name' => '党政机关',
                'code' => '5',
                'desc' => '行业类型',
                'value' => 102005,
                'created_at' => '2019-12-20 13:31:20',
                'updated_at' => '2019-12-20 13:31:20',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'type' => 'hylx',
                'name' => '企业',
                'code' => '6',
                'desc' => '行业类型',
                'value' => 102006,
                'created_at' => '2019-12-20 13:31:48',
                'updated_at' => '2019-12-20 13:31:48',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'type' => 'sblx',
                'name' => '其他',
                'code' => '1',
                'desc' => '设备类型',
                'value' => 103001,
                'created_at' => '2019-12-23 19:37:08',
                'updated_at' => '2019-12-23 19:37:08',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'type' => 'sblx',
                'name' => '可回收垃圾桶',
                'code' => '2',
                'desc' => '设备类型',
                'value' => 103002,
                'created_at' => '2019-12-23 19:37:26',
                'updated_at' => '2019-12-23 19:37:26',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'type' => 'sblx',
                'name' => '厨余垃圾桶',
                'code' => '3',
                'desc' => '设备类型',
                'value' => 103003,
                'created_at' => '2019-12-23 19:37:57',
                'updated_at' => '2019-12-23 19:37:57',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'type' => 'sblx',
                'name' => '有毒垃圾桶',
                'code' => '4',
                'desc' => '设备类型',
                'value' => 103004,
                'created_at' => '2019-12-23 19:38:19',
                'updated_at' => '2019-12-23 19:38:19',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'type' => 'sblx',
                'name' => '环保屋',
                'code' => '5',
                'desc' => '设备类型',
                'value' => 103005,
                'created_at' => '2019-12-24 21:42:31',
                'updated_at' => '2019-12-24 21:42:31',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'type' => 'sbxh',
                'name' => 'C07-98',
                'code' => '3',
                'desc' => '设备型号',
                'value' => 104003,
                'created_at' => '2019-12-23 19:40:28',
                'updated_at' => '2019-12-23 19:40:28',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'type' => 'sbxh',
                'name' => 'B06554',
                'code' => '2',
                'desc' => '设备型号',
                'value' => 104002,
                'created_at' => '2019-12-23 19:40:06',
                'updated_at' => '2019-12-23 19:40:06',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'type' => 'sbxh',
                'name' => 'A0133B',
                'code' => '1',
                'desc' => '设备型号',
                'value' => 104001,
                'created_at' => '2019-12-23 19:39:46',
                'updated_at' => '2019-12-23 19:39:46',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'type' => 'jlbz',
                'name' => '次',
                'code' => '1',
                'desc' => '计量标准',
                'value' => 105002,
                'created_at' => '2019-12-25 13:22:42',
                'updated_at' => '2019-12-25 13:22:42',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'type' => 'jlbz',
                'name' => '千克',
                'code' => '2',
                'desc' => '计量标准',
                'value' => 105003,
                'created_at' => '2019-12-25 13:22:59',
                'updated_at' => '2019-12-25 13:22:59',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'type' => 'jlbz',
                'name' => '件',
                'code' => '3',
                'desc' => '计量标准',
                'value' => 105004,
                'created_at' => '2020-07-07 19:00:41',
                'updated_at' => '2020-07-07 19:00:43',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'type' => 'jlbz',
                'name' => '桶',
                'code' => '4',
                'desc' => '计量标准',
                'value' => 105005,
                'created_at' => '2021-07-08 18:21:29',
                'updated_at' => '2021-07-08 18:21:29',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 39,
                'type' => 'sblx',
                'name' => 'A类左',
                'code' => '4',
                'desc' => '设备类型',
                'value' => 103006,
                'created_at' => '2019-12-23 19:38:19',
                'updated_at' => '2021-05-17 23:17:37',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 40,
                'type' => 'sblx',
                'name' => 'A类右',
                'code' => '4',
                'desc' => '设备类型',
                'value' => 103007,
                'created_at' => '2019-12-23 19:38:19',
                'updated_at' => '2019-12-23 19:38:19',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 43,
                'type' => 'dzlx',
                'name' => '其他',
                'code' => '10',
                'desc' => '地址类型',
                'value' => 101008,
                'created_at' => '2020-07-09 23:54:18',
                'updated_at' => '2020-07-14 19:46:28',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 44,
                'type' => 'dzlx',
                'name' => '党政机关',
                'code' => '7',
                'desc' => '地址类型',
                'value' => 101009,
                'created_at' => '2020-07-09 23:54:18',
                'updated_at' => '2020-07-14 15:52:01',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 45,
                'type' => 'dzlx',
                'name' => '学校',
                'code' => '11',
                'desc' => '地址类型',
                'value' => 101010,
                'created_at' => '2020-07-09 23:54:18',
                'updated_at' => '2020-07-09 23:54:21',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 46,
                'type' => 'dzlx',
                'name' => '机场',
                'code' => '13',
                'desc' => '地址类型',
                'value' => 101011,
                'created_at' => '2020-07-14 15:32:26',
                'updated_at' => '2020-07-14 15:34:49',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 47,
                'type' => 'dzlx',
                'name' => '物业',
                'code' => '12',
                'desc' => '地址类型',
                'value' => 101012,
                'created_at' => '2020-07-14 15:33:56',
                'updated_at' => '2020-07-14 15:33:56',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 48,
                'type' => 'dzlx',
                'name' => '事业单位',
                'code' => '8',
                'desc' => '地址类型',
                'value' => 101013,
                'created_at' => '2020-07-14 16:24:53',
                'updated_at' => '2020-07-14 16:24:53',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 49,
                'type' => 'dzlx',
                'name' => '公交站场',
                'code' => '9',
                'desc' => '地址类型',
                'value' => 101014,
                'created_at' => '2020-07-14 16:25:27',
                'updated_at' => '2020-07-14 16:30:40',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 50,
                'type' => 'clpp',
                'name' => '雷诺',
                'code' => '1',
                'desc' => '车辆品牌',
                'value' => 106001,
                'created_at' => '2020-12-28 16:48:18',
                'updated_at' => '2020-12-28 16:48:18',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 51,
                'type' => 'clpp',
                'name' => '东风',
                'code' => '2',
                'desc' => '车辆品牌',
                'value' => 106002,
                'created_at' => '2020-12-28 16:48:18',
                'updated_at' => '2020-12-28 16:48:18',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 52,
                'type' => 'rllx',
                'name' => '汽油',
                'code' => '14',
                'desc' => '燃料类型',
                'value' => 107001,
                'created_at' => '2021-02-03 14:12:30',
                'updated_at' => '2021-02-03 14:12:30',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 53,
                'type' => 'rllx',
                'name' => '柴油',
                'code' => '14',
                'desc' => '燃料类型',
                'value' => 107002,
                'created_at' => '2021-02-03 14:13:04',
                'updated_at' => '2021-02-03 14:13:04',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 62,
                'type' => 'khlb',
                'name' => '日常考核',
                'code' => '0',
                'desc' => '考核类别 ',
                'value' => 109001,
                'created_at' => '2021-02-19 16:18:53',
                'updated_at' => '2021-02-19 16:18:53',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 63,
                'type' => 'khlb',
                'name' => '集中考核',
                'code' => '1',
                'desc' => '考核类别',
                'value' => 109002,
                'created_at' => '2021-02-19 16:19:20',
                'updated_at' => '2021-02-19 16:19:20',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 64,
                'type' => 'dwlx',
                'name' => '运营单位',
                'code' => '1',
                'desc' => '单位类型',
                'value' => 110001,
                'created_at' => '2021-02-25 12:28:51',
                'updated_at' => '2021-06-11 14:41:12',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 65,
                'type' => 'dwlx',
                'name' => '管理单位',
                'code' => '2',
                'desc' => '单位类型',
                'value' => 110002,
                'created_at' => '2021-02-25 12:28:51',
                'updated_at' => '2021-02-25 12:28:51',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 66,
                'type' => 'dwlx',
                'name' => '责任单位',
                'code' => '2',
                'desc' => '单位类型',
                'value' => 110003,
                'created_at' => '2021-02-25 12:28:51',
                'updated_at' => '2021-06-11 14:40:56',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 67,
                'type' => 'pfbz',
                'name' => '不合格',
                'code' => '0',
                'desc' => '评分标准',
                'value' => 120001,
                'created_at' => '2021-03-02 00:14:41',
                'updated_at' => '2021-03-02 00:14:41',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 68,
                'type' => 'pfbz',
                'name' => '合格',
                'code' => '1',
                'desc' => '评分标准',
                'value' => 120002,
                'created_at' => '2021-03-02 00:14:41',
                'updated_at' => '2021-03-02 00:14:41',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 71,
                'type' => 'zyz',
                'name' => '各类再生资源处理设施',
                'code' => '0',
                'desc' => '转运站类型',
                'value' => 121001,
                'created_at' => '2021-03-11 20:10:50',
                'updated_at' => '2021-03-11 20:10:50',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 72,
                'type' => 'zyz',
                'name' => '各类危废处理设施',
                'code' => '0',
                'desc' => '转运站类型',
                'value' => 121002,
                'created_at' => '2021-03-11 20:10:50',
                'updated_at' => '2021-03-11 20:10:50',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 73,
                'type' => 'zyz',
                'name' => '焚烧处理设备、卫生填埋场',
                'code' => '0',
                'desc' => '转运站类型',
                'value' => 121003,
                'created_at' => '2021-03-11 20:10:50',
                'updated_at' => '2021-03-11 20:10:50',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 74,
                'type' => 'zyz',
                'name' => '厨余垃圾转运站',
                'code' => '0',
                'desc' => '转运站类型',
                'value' => 121004,
                'created_at' => '2021-03-11 20:10:50',
                'updated_at' => '2021-06-29 16:50:05',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 79,
                'type' => 'kfjz',
                'name' => '总分制',
                'code' => '0',
                'desc' => '扣分机制',
                'value' => 123001,
                'created_at' => '2021-04-23 09:00:14',
                'updated_at' => '2021-04-23 09:00:14',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 80,
                'type' => 'kfjz',
                'name' => '百分比',
                'code' => '0',
                'desc' => '扣分机制',
                'value' => 123002,
                'created_at' => '2021-04-23 09:00:14',
                'updated_at' => '2021-04-23 09:00:14',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 81,
                'type' => 'kfjz',
                'name' => '奖励制',
                'code' => '0',
                'desc' => '扣分机制',
                'value' => 123003,
                'created_at' => '2021-04-23 09:00:14',
                'updated_at' => '2021-04-23 09:00:14',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 85,
                'type' => 'sblx',
                'name' => 'B类左',
                'code' => '5',
                'desc' => '设备类型',
                'value' => 103008,
                'created_at' => '2021-05-25 09:23:56',
                'updated_at' => '2021-05-25 09:23:56',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 86,
                'type' => 'sblx',
                'name' => 'B类右',
                'code' => '6',
                'desc' => '设备类型',
                'value' => 103009,
                'created_at' => '2021-05-25 09:24:19',
                'updated_at' => '2021-05-25 09:24:19',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 87,
                'type' => 'cflx',
                'name' => '1倍扣分',
                'code' => '1',
                'desc' => '处罚类型',
                'value' => 124001,
                'created_at' => '2021-05-26 12:58:29',
                'updated_at' => '2021-05-26 12:58:29',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 88,
                'type' => 'cflx',
                'name' => '2倍扣分',
                'code' => '2',
                'desc' => '处罚类型',
                'value' => 124002,
                'created_at' => '2021-05-26 12:58:29',
                'updated_at' => '2021-05-26 12:58:29',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 89,
                'type' => 'cflx',
                'name' => '3倍扣分',
                'code' => '3',
                'desc' => '处罚类型',
                'value' => 124003,
                'created_at' => '2021-05-26 12:58:48',
                'updated_at' => '2021-05-26 12:58:48',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 90,
                'type' => 'cflx',
                'name' => '5倍扣分',
                'code' => '5',
                'desc' => '处罚类型',
                'value' => 124004,
                'created_at' => '2021-05-26 12:59:06',
                'updated_at' => '2021-05-26 12:59:06',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 91,
                'type' => 'khlx',
                'name' => '日常考核',
                'code' => '1',
                'desc' => '考核类型',
                'value' => 125001,
                'created_at' => '2021-05-26 13:13:43',
                'updated_at' => '2021-05-26 13:13:43',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 92,
                'type' => 'khlx',
                'name' => '集中考核',
                'code' => '2',
                'desc' => '考核类型',
                'value' => 125002,
                'created_at' => '2021-05-26 13:14:01',
                'updated_at' => '2021-05-26 13:14:01',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 93,
                'type' => 'khlx',
                'name' => '集中考核',
                'code' => '2',
                'desc' => '考核类型',
                'value' => 125002,
                'created_at' => '2021-05-26 13:14:01',
                'updated_at' => '2021-05-26 13:14:01',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 94,
                'type' => 'zyz',
                'name' => '生活垃圾转运站',
                'code' => '1',
                'desc' => '转运站类型',
                'value' => 121005,
                'created_at' => '2021-06-22 22:03:48',
                'updated_at' => '2021-06-22 22:03:48',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 95,
                'type' => 'rllx',
                'name' => '电动车',
                'code' => '0',
                'desc' => '燃料类型',
                'value' => 107003,
                'created_at' => '2021-06-23 23:12:49',
                'updated_at' => '2021-06-23 23:12:49',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 96,
                'type' => 'dwlx',
                'name' => '早餐点运营单位',
                'code' => '3',
                'desc' => '单位类型',
                'value' => 110004,
                'created_at' => '2021-07-10 21:19:52',
                'updated_at' => '2021-07-10 21:19:52',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 97,
                'type' => 'wglx',
                'name' => '规范经营',
                'code' => '0',
                'desc' => '违规类型',
                'value' => 125001,
                'created_at' => '2021-07-11 12:51:05',
                'updated_at' => '2021-07-11 12:51:05',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 98,
                'type' => 'wglx',
                'name' => '环境卫生',
                'code' => '1',
                'desc' => '违规类型',
                'value' => 125002,
                'created_at' => '2021-07-11 12:51:34',
                'updated_at' => '2021-07-11 12:51:34',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 99,
                'type' => 'wglx',
                'name' => '其它',
                'code' => '2',
                'desc' => '违规类型',
                'value' => 125003,
                'created_at' => '2021-07-11 12:51:50',
                'updated_at' => '2021-07-11 12:51:50',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 100,
                'type' => 'dzlx',
                'name' => '居委会',
                'code' => '1',
                'desc' => '地址类型',
                'value' => 101015,
                'created_at' => '2019-11-29 12:06:33',
                'updated_at' => '2019-11-29 12:06:33',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 101,
                'type' => 'sblx',
                'name' => 'C类左',
                'code' => '7',
                'desc' => '设备类型',
                'value' => 103010,
                'created_at' => '2021-09-03 20:15:34',
                'updated_at' => '2021-09-03 20:16:42',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 102,
                'type' => 'sblx',
                'name' => 'C类右',
                'code' => '8',
                'desc' => '设备类型',
                'value' => 130011,
                'created_at' => '2021-09-03 20:16:22',
                'updated_at' => '2021-09-03 20:17:02',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}